### ISSUE TITLE
linux 64 bit problem

### ISSUE THREAD

**Issue by pietrondo** [totovr/SimpleOpenNI#1]
Hello on archlinux (64 bit)
i try to install the library but... appear this message:

`Or only works properly when the sketch is run as a 32-bit application.`

is not a 64 library?
thx

**Comment by totovr** [comment]
Hello! 

I have tasted in MacOS Sierra and is working, I haven't a computer with linux to check it, did you try with the 2.2.1 version?

**Comment by pietrondo** [comment]
ok.. where is the source? so i try to compile for my pc?
thx

**Comment by totovr** [comment]
This is the branch:

* [2.2.1V](https://github.com/totovr/SimpleOpenni/tree/Processing_2.2.1)

**Comment by pietrondo** [comment]
No.. I'm looking the code to try to compile to processing 3 (i need some library enabled only on 3)
thx for the help

**Comment by totovr** [comment]
Sorry but as I said above, is just tasted in Mac

**Comment by totovr** [comment]
Can you try this [file](https://github.com/totovr/SimpleOpenni/files/1622455/linux64.zip)

* Replace it in: 

      SimpleOpenni > library

**Comment by makenb** [comment]
Hi,
I tested with your updated linux64 file on Ubuntu 17.04 however it gives an error:

`libboost_system.so.1.54.0: cannot open shared object file: no such file or directory`

I have libboost 1.63.0 installed, there is no 1.54.0 package available

**Comment by totovr** [comment]
Is it possible to downgrade it?

http://www.boost.org/users/history/version_1_54_0.html
