### ISSUE TITLE
Licesing Concerns?

### ISSUE THREAD

**Issue by TroikaTronix** [totovr/SimpleOpenNI#11]
### Issue Summary

Does including NiTE violate their license?

### Type of Issue
- Question

So, I was planning to put out a NiTE module for Isadora and a user posted this:

How did you get around NiTE's licensing restrictions, which prohibit using it with non-Primesense devices and prohibit redistributing it?

with this link going to an archive of Prime Sense's license

http://web.archive.org/web/20140305024832/http://www.openni.org/nite-licensing-and-distribution-terms/

Not that any of you are lawyers, but does anyone have an opinion about this? I mean, there are loads of copies of NiTE running around the web. It doesn't seem like Apple (who bought Prime Sense) is going after anyone, but I thought I'd mention it since you're hosting NiTE in ths github.

Best WIshes,
Mark

**Comment by totovr** [comment]
Hello! I haven't read before about this issue, also as you said there are many copies of NiTE around the web, but I have not received any warning from Apple, So if there is any problem in future I will shut off the repository.
