### ISSUE TITLE
Question: to find implementation of userImage()

### ISSUE THREAD

**Issue by smokhov** [totovr/SimpleOpenNI#13]
### Issue Summary

We are looking for the implementation of the `userImage()` method to port its functionality to another device. It seems no source code is provided for it in the `.jar`s. Where does the implementation come from and how one can access it?

### Type of Issue

- Question

**Comment by totovr** [comment]
<img width="927" alt="screen shot 2019-02-17 at 10 54 39" src="https://user-images.githubusercontent.com/15333235/52907304-7fb26800-32a2-11e9-91cb-be67d836be14.png">

**Comment by smokhov** [comment]
I guess I need to be clearer :) We are looking for either `ContextWrapper.java` or `ContextWrapper.cpp` from which you compiled .jar/.dylib/.so/.dll and not exactly their javadoc or doxygen.

**Comment by smokhov** [comment]
@totovr:  I've redownloaded the original sources of `SimpleOpenNI` from https://code.google.com/archive/p/simple-openni/source/default/source and have found what we were looking for, more or less (FYI, @dongbeikezhenxi). The question is are you still using the exact the same sources for this project to compile the binaries or do you use some updated sources for it?

**Comment by totovr** [comment]
I used and modified from [wexstorm](https://github.com/wexstorm/simple-openni)
