### ISSUE TITLE
Could anyone got it working on Linux/Ubuntu?

### ISSUE THREAD

**Issue by rossanag** [totovr/SimpleOpenNI#24]
Hi, I am aware it was developed for Mac, but since there are Linux libraries into the branch I took the shot. However, it doesn't work on Ubuntu, maybe I am missing some step.
This line is highlighted in the code:
` context = new SimpleOpenNI(this);`

And the message of the error is the following:

> Can't load SimpleOpenNI library (libSimpleOpenNI64.so) : java.lang.UnsatisfiedLinkError: /home/rossana/sketchbook/libraries/SimpleOpenNI/library/libSimpleOpenNI64.so: libboost_system.so.1.54.0: no se puede abrir el archivo del objeto compartido: No existe el archivo o el directorio
> Verify if you installed SimpleOpenNI correctly.
> http://code.google.com/p/simple-openni/wiki/Installation
> UnsatisfiedLinkError: SimpleOpenNI.SimpleOpenNIJNI.swig_module_init()V
> UnsatisfiedLinkError: SimpleOpenNI.SimpleOpenNIJNI.swig_module_init()V
> A library relies on native code that's not available.
> Or only works properly when the sketch is run as a 32-bit application.

It says it cant' open libboost_system.so.1.54.0 file , because it doesn' t exist, however it is in the folder. I downloaded the 64 bit version. 
Thanks in advance.

SO: Ubuntu 19.04
Kinect v1 1414

**Comment by pointcloudAI** [comment]
you can try to run command as below :
```
locate libboost_system.so 1.5*
```
Get the path of your libboost_system and create soft link as  libboost_system.so.1.54.0 

```
ln -s  your_path/libboost_system.so.1.58.0  your_path/libboost_system.so.1.54.0 
```

**Comment by rossanag** [comment]
> ln -s  your_path/libboost_system.so.1.58.0  your_path/libboost_system.so.1.54.0

Thanks for the suggestion, I did what you said, no luck though, still the same error,

Are you a linux user with Processing 3? if so, I want to know the steps you follow.
Best!

**Comment by pointcloud-ai** [comment]
@rossanag  Yes ,it work on my ubuntu 18.04

`sudo ln -s  /usr/lib/x86_64-linux-gnu/libboost_system.so.1.50.0  /usr/lib/x86_64-linux-gnu/libboost_system.so.1.54.0 
`

**Comment by pointcloud-ai** [comment]
@rossanag  Yes ,it work on my ubuntu 18.04

`sudo ln -s  /usr/lib/x86_64-linux-gnu/libboost_system.so.1.50.0  /usr/lib/x86_64-linux-gnu/libboost_system.so.1.54.0 
`

**Comment by rossanag** [comment]
Finally I got it working on Ubuntu 19.10. My mistake was that I created the softlink where the Processing library is in the sketchbook folder instead of this creating it in this one  /usr/lib/x86_64-linux-gnu/. 
I installed SimpleOpenNI again, and I created the softlink afterwards.
Thank @pointcloud-ai for gave me that hint with your post.

Best!
