### ISSUE TITLE
SimpleOpenni hangs on `context = new SimpleOpenNI(this);`

### ISSUE THREAD

**Issue by clankill3r** [totovr/SimpleOpenNI#4]
On OSX I don't get further then:

context = new SimpleOpenNI(this);

Apart from moving the folder to the processing library folder,
is there anything else I need to do?

**Comment by totovr** [comment]
Yes you have to download the library and paste it in the processing libraries folder.

- The documentation is [index.htlm](https://www.youtube.com/watch?v=dimAM_GTU0o)

> I have some examples [here](https://github.com/totovr/Processing/tree/Processing-3.3.6/Kinect/Kinect_SimpleOpenni)
