### ISSUE TITLE
Kinect V2 doesn't initialize on macOS

### ISSUE THREAD

**Issue by eccoscreen** [totovr/SimpleOpenNI#5]
### Issue Summary
Hi I've got an issue with initializing Kinect V2 on Processing 3.3.7, it doesn't initialize. Everything is plugged in correctly. The Kinect V1 works just fine. I've also tested the Kinect V2 in another library (Open Kinect for Processing) and it works there fine, but for this I'm not getting any response. Do you know what might be going on? Thanks

### Executed Command (if any)
```
kinect  = new SimpleOpenNI(this);
kinect.enableDepth();
```
### Processing Output (if any)
```
SimpleOpenNI Version 1.96
After initialization:

SimpleOpenNI Error: Can't open device:		DeviceOpen using default: no devices found


SimpleOpenNI not initialised
```

### Type of Issue
- Execution error

### System Configuration
**Operating system**: macOS High Sierra 10.13.4
Kinect V2
Processing 3.3.7

**Comment by totovr** [comment]
Hello! 
Did you install all the dependencies of:
*  libfreenect2
*  NiTE?

**Comment by eccoscreen** [comment]
Ah yeah that did it. Looks like something didn't install the first time I went through that process. Thanks

**Comment by totovr** [comment]
The **detail** is here:

![Installation Process](https://user-images.githubusercontent.com/15333235/40694436-7cfd2750-63f7-11e8-9edc-3e8e80e3c56b.png)

**Comment by totovr** [comment]
Can I close the **Issue**?

**Comment by dwhit** [comment]
Hey I seem to be having the same issue as @eccoscreen. I followed the install instructions [here](https://github.com/totovr/SimpleOpenNI/blob/master/instructions.md) but I get the error from above.

**Comment by totovr** [comment]
Did you installed `OpenNI2`?

**Comment by dwhit** [comment]
through brew, yes. And I added the environment variables to my .zshrc

**Comment by dwhit** [comment]
I can run Protonect, and I also downloaded NiTE separately, and can run those samples (eg UserViewer)

**Comment by dwhit** [comment]
Okay I figured it out. I needed to copy libfreenect2/build/lib/libfreenect2-openni2.0.dylib from the manual install folder into the SimpleOpenNI processing folder. Also set LIBFREENECT2_PIPELINE=cl in my environment.
